services:

  # Selenium
  selenium-chrome:
    profiles: [chrome]
    image: selenium/standalone-chrome:129.0
    container_name: selenium
    ports:
      - "4444:4444"  # Expose the WebDriver port
    shm_size: '2gb'  # Increase shared memory size to prevent browser crashes

  selenium-firefox:
    profiles: [firefox]
    image: selenium/standalone-firefox:130.0
    container_name: selenium
    ports:
      - "4444:4444"  # Expose the WebDriver port
    shm_size: '2gb'  # Increase shared memory size to prevent browser crashes

  # Python app
  app:
    profiles: [chrome, firefox]
    build:
      context: ./
      dockerfile: ./docker/Dockerfiles/python-3.10/Dockerfile
    container_name: app
    environment:
      - HOST_USER_ID=${UID}
      - HOST_USER_GROUP_ID=${GID}
    volumes:
      - ./app:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    # command: python /app/app.py
    command: tail -f /dev/null

  doccano:
    profiles: [chrome, firefox]
    image: doccano/doccano
    container_name: doccano
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=secret
    volumes:
      - ./doccano/data:/data
    ports:
      - "8000:8000"
  

#Docker Networks
networks:
  lumen:
    driver: bridge
